services:
  - name: backend
    startCommand: node server.js
    buildCommand: npm install

routes:
  - path: /api
    destination: backend

files:
  - source: cors.json
    mount: /backend/cors.json
